name=EspNowDev
version=1.0.0
author=AutoPort
maintainer=AutoPort<irawanzuly11@gmail.com>
sentence=Fast communication library for ESP32 interconnectivity.
paragraph=Supports AES encryption and a hybrid protocol combining ESP-NOW and WebSockets.
category=Communication
url=https://github.com/mulberry4275/EspNowDev
architectures=esp32
